name: 'app-deployment'
on:
workflow_dispatch:
push:
# branches-ignore:
branches:
- 'main' 	 
jobs:
 application_deployment:
   runs-on: ubuntu-latest
   env:
     ACR_URL: '.azurecr.io'
     ACR_USERNAME: ''
     ACR_PASSWORD: '${{ secrets.ACR_PASSWORD }}'

steps:
  - name: 'Checkout repository'
    uses: actions/checkout@v2

  - name: 'Login to ACR ${{ env.ACR_URL }}'
    uses: docker/login-action@v1
    with:
   registry: ${{ env.ACR_URL }}
   username: ${{ env.ACR_USERNAME }}
   password: ${{ secrets.ACR_PASSWORD }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
    id: build

-name: Docker Build
  run: docker build -t amir_cld_ui .

- name: Docker Tag
  run: docker tag amir_cld_api ${{ env.ACR_URL }}/amir_cld_ui

- name: Docker Image Push
  run: docker image push ${{ env.ACR_URL }}/amir_cld_ui
